.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-skills-paths 1  "paths " 
.SH NAME
devin\-skills\-paths \- Show skill directory locations
.SH SYNOPSIS
\fBdevin skills paths\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show skill directory locations
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
