.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-help-cloud-drs-blueprint-create 1  "blueprint-create " 
.SH NAME
devin\-help\-cloud\-drs\-blueprint\-create \- Create a new environment blueprint
.SH SYNOPSIS
\fBdevin help cloud drs blueprint\-create\fR 
.SH DESCRIPTION
Create a new environment blueprint
