.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-help-cloud-drs-build-start 1  "build-start " 
.SH NAME
devin\-help\-cloud\-drs\-build\-start \- Trigger an environment build without waiting
.SH SYNOPSIS
\fBdevin help cloud drs build\-start\fR 
.SH DESCRIPTION
Trigger an environment build without waiting
