.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-mcp-remove 1  "remove " 
.SH NAME
devin\-mcp\-remove \- Remove an MCP server
.SH SYNOPSIS
\fBdevin mcp remove\fR [\fB\-s\fR|\fB\-\-scope\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Remove an MCP server
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-scope\fR \fI<SCOPE>\fR [default: local]
Configuration scope
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
local: Local project config, not committed (.devin/config.local.json)
.IP \(bu 2
project: Project\-level config (.devin/config.json)
.IP \(bu 2
user: User\-level config (~/.config/devin/config.json)
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fINAME\fR>
Server name
