.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-cloud-drs-help-blueprint-create 1  "blueprint-create " 
.SH NAME
devin\-cloud\-drs\-help\-blueprint\-create \- Create a new environment blueprint
.SH SYNOPSIS
\fBdevin cloud drs help blueprint\-create\fR 
.SH DESCRIPTION
Create a new environment blueprint
