.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-skills-show 1  "show " 
.SH NAME
devin\-skills\-show \- Show details for a specific skill
.SH SYNOPSIS
\fBdevin skills show\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Show details for a specific skill
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Skill name
