.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-auth-logout 1  "logout " 
.SH NAME
devin\-auth\-logout \- Log out and remove stored credentials
.SH SYNOPSIS
\fBdevin auth logout\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Log out and remove stored credentials
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
