.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-help-rules 1  "rules " 
.SH NAME
devin\-help\-rules \- Manage agent rules (always\-on context blobs)
.SH SYNOPSIS
\fBdevin help rules\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Manage agent rules (always\-on context blobs)
.SH SUBCOMMANDS
.TP
devin\-help\-rules\-list(1)
List all available rules
.TP
devin\-help\-rules\-show(1)
Show details for a specific rule
.TP
devin\-help\-rules\-paths(1)
Show rule directory locations
