.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-help-auth 1  "auth " 
.SH NAME
devin\-help\-auth \- Authentication related commands
.SH SYNOPSIS
\fBdevin help auth\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Authentication related commands
.SH SUBCOMMANDS
.TP
devin\-help\-auth\-login(1)
Log in to Windsurf
.TP
devin\-help\-auth\-logout(1)
Log out and remove stored credentials
.TP
devin\-help\-auth\-status(1)
Check authentication status
