.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-mcp-logout 1  "logout " 
.SH NAME
devin\-mcp\-logout \- Remove stored OAuth credentials for an MCP server
.SH SYNOPSIS
\fBdevin mcp logout\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Remove stored OAuth credentials for an MCP server
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Server name to logout from
