.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-cloud-drs-blueprint-list 1  "blueprint-list " 
.SH NAME
devin\-cloud\-drs\-blueprint\-list \- List all environment blueprints for the organization
.SH SYNOPSIS
\fBdevin cloud drs blueprint\-list\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List all environment blueprints for the organization
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
