.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-help-shell 1  "shell " 
.SH NAME
devin\-help\-shell \- [Feature preview] Integrate with your shell to instantly launch devin with relevant context
.SH SYNOPSIS
\fBdevin help shell\fR [\fIsubcommands\fR]
.SH DESCRIPTION
[Feature preview] Integrate with your shell to instantly launch devin with relevant context
.SH SUBCOMMANDS
.TP
devin\-help\-shell\-init(1)
Output shell integration script for eval
.TP
devin\-help\-shell\-run(1)
Run the shell wrapper
.TP
devin\-help\-shell\-setup(1)
Install shell integration into config files
