.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-sandbox-setup 1  "setup " 
.SH NAME
devin\-sandbox\-setup \- [Research Preview] Provision the sandbox environment
.SH SYNOPSIS
\fBdevin sandbox setup\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
[Research Preview] Provision the sandbox environment
.PP
On Linux, verifies that bubblewrap (bwrap) is installed. macOS sandboxing (seatbelt) works out of the box.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
