.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-help-cloud 1  "cloud " 
.SH NAME
devin\-help\-cloud \- Manage Devin Cloud resources (environment setup, sandbox sessions, builds)
.SH SYNOPSIS
\fBdevin help cloud\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Manage Devin Cloud resources (environment setup, sandbox sessions, builds)
.SH SUBCOMMANDS
.TP
devin\-help\-cloud\-drs(1)
Manage Declarative Repo Setup (environment blueprints, sandbox sessions, and builds)
