.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-cloud-help-drs-build-start 1  "build-start " 
.SH NAME
devin\-cloud\-help\-drs\-build\-start \- Trigger an environment build without waiting
.SH SYNOPSIS
\fBdevin cloud help drs build\-start\fR 
.SH DESCRIPTION
Trigger an environment build without waiting
