.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-uninstall 1  "uninstall " 
.SH NAME
devin\-uninstall \- Uninstall and remove data
.SH SYNOPSIS
\fBdevin uninstall\fR [\fB\-\-clean\fR] [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Uninstall and remove data
.SH OPTIONS
.TP
\fB\-\-clean\fR
Remove all user data

Includes configuration, history, and custom data.
.TP
\fB\-\-force\fR
Skip confirmation prompt
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
