.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-mcp-get 1  "get " 
.SH NAME
devin\-mcp\-get \- Get details for a specific MCP server
.SH SYNOPSIS
\fBdevin mcp get\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Get details for a specific MCP server
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Server name
