.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-cloud-drs-whoami 1  "whoami " 
.SH NAME
devin\-cloud\-drs\-whoami \- Print the current DRS configuration (org, API endpoint, auth status)
.SH SYNOPSIS
\fBdevin cloud drs whoami\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Print the current DRS configuration (org, API endpoint, auth status)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
