.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-update 1  "update " 
.SH NAME
devin\-update \- Check for updates and optionally install them
.SH SYNOPSIS
\fBdevin update\fR [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Check for updates and optionally install them
.SH OPTIONS
.TP
\fB\-\-force\fR
Force re\-install even if already on the latest version
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
