.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-rules-show 1  "show " 
.SH NAME
devin\-rules\-show \- Show details for a specific rule
.SH SYNOPSIS
\fBdevin rules show\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Show details for a specific rule
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Rule name or ID
