.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-cloud-drs-secret-create 1  "secret-create " 
.SH NAME
devin\-cloud\-drs\-secret\-create \- Create an organization\-level secret
.SH SYNOPSIS
\fBdevin cloud drs secret\-create\fR <\fB\-\-key\fR> <\fB\-\-value\fR> [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Create an organization\-level secret
.SH OPTIONS
.TP
\fB\-\-key\fR \fI<KEY>\fR
Secret name
.TP
\fB\-\-value\fR \fI<VALUE>\fR
Secret value
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
