.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-auth-help 1  "help " 
.SH NAME
devin\-auth\-help \- Print this message or the help of the given subcommand(s)
.SH SYNOPSIS
\fBdevin auth help\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Print this message or the help of the given subcommand(s)
.SH SUBCOMMANDS
.TP
devin\-auth\-help\-login(1)
Log in to Windsurf
.TP
devin\-auth\-help\-logout(1)
Log out and remove stored credentials
.TP
devin\-auth\-help\-status(1)
Check authentication status
.TP
devin\-auth\-help\-help(1)
Print this message or the help of the given subcommand(s)
