.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devin-help-cloud-drs-blueprint-list 1  "blueprint-list " 
.SH NAME
devin\-help\-cloud\-drs\-blueprint\-list \- List all environment blueprints for the organization
.SH SYNOPSIS
\fBdevin help cloud drs blueprint\-list\fR 
.SH DESCRIPTION
List all environment blueprints for the organization
